name: Render manifests
on:
  push:
    branches:
      - main

permissions: 
  contents: write
  pull-requests: write

# See: https://github.com/akuity/kargo-render/issues/249
env:
  XDG_CONFIG_HOME: /tmp
  XDG_CACHE_HOME: /tmp
  XDG_DATA_HOME: /tmp

jobs:
  render-dev-manifests:
    name: Render `dev` manifests
    runs-on: ubuntu-latest
    steps:
    - name: Render manifests
      uses: akuity/kargo-render-action@v0.1.0-rc.35
      with:
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: env/dev
  
  render-test-manifests:
    name: Render `test` manifests
    runs-on: ubuntu-latest
    steps:
    - name: Render manifests
      uses: akuity/kargo-render-action@v0.1.0-rc.35
      with:
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: env/test

  render-uat-manifests:
    name: Render `uat` manifests
    runs-on: ubuntu-latest
    steps:
    - name: Render manifests
      uses: akuity/kargo-render-action@v0.1.0-rc.35
      with:
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: env/uat

  render-prod-manifests:
    name: Render `prod` manifests
    runs-on: ubuntu-latest
    steps:
    - name: Render manifests
      uses: akuity/kargo-render-action@v0.1.0-rc.35
      with:
        personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: env/prod
